name: Build project
on:
  push:
    branches: [ master ]
    paths:
      - xtreeve/**
      - .github/workflows/project-build.yml

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: cd xtreeve && mvn compile verify package
